// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQeH1y8dP84jPxvvaXuUfyXv4qTM7DmGg',
    appId: '1:1025055086151:web:9cd41c610b485736a1c362',
    messagingSenderId: '1025055086151',
    projectId: 'kenya-at-fifty',
    authDomain: 'kenya-at-fifty.firebaseapp.com',
    storageBucket: 'kenya-at-fifty.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1qrq8wOxm1eTqR1P6x-4kQ5jGO0Gao4',
    appId: '1:1025055086151:android:6801bc1b742de3fea1c362',
    messagingSenderId: '1025055086151',
    projectId: 'kenya-at-fifty',
    storageBucket: 'kenya-at-fifty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqBY-Y9eI3D_Ag17g7fM6rgZ3aW2TPfqY',
    appId: '1:1025055086151:ios:dfcf0b14b42634c9a1c362',
    messagingSenderId: '1025055086151',
    projectId: 'kenya-at-fifty',
    storageBucket: 'kenya-at-fifty.firebasestorage.app',
    iosBundleId: 'com.example.kenyanGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqBY-Y9eI3D_Ag17g7fM6rgZ3aW2TPfqY',
    appId: '1:1025055086151:ios:dfcf0b14b42634c9a1c362',
    messagingSenderId: '1025055086151',
    projectId: 'kenya-at-fifty',
    storageBucket: 'kenya-at-fifty.firebasestorage.app',
    iosBundleId: 'com.example.kenyanGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQeH1y8dP84jPxvvaXuUfyXv4qTM7DmGg',
    appId: '1:1025055086151:web:c556404cb9c21036a1c362',
    messagingSenderId: '1025055086151',
    projectId: 'kenya-at-fifty',
    authDomain: 'kenya-at-fifty.firebaseapp.com',
    storageBucket: 'kenya-at-fifty.firebasestorage.app',
  );
}
